SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

-- Tab 1
SELECT DISTINCT
    CONCAT(P.PDVENDOR, P.PDNUMBER, P.PDSTORE) AS `UID`,
    P.PDVENDOR,
    P.PDNUMBER,
    P.PDSTORE,
    P.PDDESCRIP,
    P.PDINVMEMO,
    P.PDACTCOST,
    D.TPDHSPRIC1,
    ROUND(D.TPDHSPRIC1 * 0.96, 2) AS `New ACT Cost`,
    ROUND(P.PDACTCOST - (D.TPDHSPRIC1 * 0.96), 2) AS `Change`
FROM DTA273.TMPROD P
INNER JOIN KMTDTA.STORES S
    ON P.PDSTORE = S.STORENUM
   AND S.ACTIVE = 'Y'
LEFT JOIN DTA273.TMPDHS D
    ON D.TPDHSNBPD = P.PDNUMBER
WHERE P.PDDELETE = 'A'
  AND P.PDFLGUSR6 = 'S'
  AND P.PDINVMEMO > 0
  AND (P.PDACTCOST - D.TPDHSPRIC1) > 0;


-- Tab 2
SELECT DISTINCT
    CONCAT(P.PDVENDOR, P.PDNUMBER, P.PDSTORE) AS `UID`,
    P.PDVENDOR,
    P.PDNUMBER,
    P.PDSTORE,
    P.PDDESCRIP,
    P.PDINVMEMO,
    P.PDACTCOST,
    D.TPDHSPRIC1,
    ROUND(D.TPDHSPRIC1 * 0.96, 2) AS `New ACT Cost`,
    ROUND(P.PDACTCOST - (D.TPDHSPRIC1 * 0.96), 2) AS `Change`
FROM DTA273.TMPROD P
INNER JOIN KMTDTA.STORES S
    ON P.PDSTORE = S.STORENUM
   AND S.ACTIVE = 'Y'
LEFT JOIN DTA273.TMPDHS D
    ON D.TPDHSNBPD = P.PDNUMBER
WHERE P.PDDELETE = 'A'
  AND P.PDFLGUSR6 = 'S'
  AND P.PDINVMEMO > 0
  AND (D.TPDHSPRIC1 - P.PDACTCOST) >= .03;


-- Tab 3
SELECT DISTINCT
    CONCAT(P.PDVENDOR, P.PDNUMBER, P.PDSTORE) AS `UID`,
    P.PDVENDOR,
    P.PDNUMBER,
    P.PDSTORE,
    P.PDDESCRIP,
    P.PDINVMEMO,
    P.PDACTCOST,
    P.PDPRICE3,
    ROUND(P.PDPRICE3 * 0.96, 2) AS `New ACT Cost`
FROM DTA273.TMPROD P
INNER JOIN KMTDTA.STORES S
    ON P.PDSTORE = S.STORENUM
   AND S.ACTIVE = 'Y'
WHERE P.PDDELETE = 'A'
  AND P.PDFLGUSR6 <> 'S'
  AND P.PDINVMEMO > 0
  AND P.PDCLASS BETWEEN '01' AND '21'
  AND (P.PDPRICE3 - P.PDACTCOST) < (P.PDPRICE3 * .03);


-- Tab 4
SELECT DISTINCT
    CONCAT(P.PDVENDOR, P.PDNUMBER, P.PDSTORE) AS `UID`,
    P.PDVENDOR,
    P.PDNUMBER,
    P.PDSTORE,
    P.PDDESCRIP,
    P.PDINVMEMO,
    P.PDACTCOST,
    P.PDREPLCOST,
    ROUND(P.PDACTCOST * .03, 2) AS `3%`,
    ROUND(P.PDACTCOST - P.PDREPLCOST, 2) AS `AC-RC`,
    ROUND(P.PDINVMEMO * (P.PDACTCOST - P.PDREPLCOST), 2) AS `Change`
FROM DTA273.TMPROD P
INNER JOIN KMTDTA.STORES S
    ON P.PDSTORE = S.STORENUM
   AND S.ACTIVE = 'Y'
WHERE P.PDDELETE = 'A'
  AND P.PDFLGUSR6 <> 'S'
  AND P.PDACTCOST <> 0
  AND P.PDCLASS BETWEEN '01' AND '21'
  AND (P.PDACTCOST - P.PDREPLCOST) / P.PDACTCOST >= .03;


-- Tab 5
SELECT DISTINCT
    CONCAT(P.PDVENDOR, P.PDNUMBER, P.PDSTORE) AS `UID`,
    P.PDVENDOR,
    P.PDNUMBER,
    P.PDSTORE,
    P.PDDESCRIP,
    P.PDINVMEMO,
    P.PDACTCOST,
    P.PDREPLCOST,
    ROUND(P.PDREPLCOST * .03, 2) AS `RC x 3%`,
    ROUND(P.PDREPLCOST - P.PDACTCOST, 2) AS `RC-AC`,
    ROUND(P.PDINVMEMO * (P.PDREPLCOST - P.PDACTCOST), 2) AS `Change`
FROM DTA273.TMPROD P
INNER JOIN KMTDTA.STORES S
    ON P.PDSTORE = S.STORENUM
   AND S.ACTIVE = 'Y'
WHERE P.PDDELETE = 'A'
  AND P.PDFLGUSR6 <> 'S'
  AND P.PDACTCOST <> 0
  AND P.PDCLASS BETWEEN '01' AND '21'
  AND (P.PDREPLCOST - P.PDACTCOST) / P.PDREPLCOST >= .03;