SELECT 
CUNUMBER AS 'CUSTOMER #',
CUNAME AS 'CUSTOMER NAME',
CURVCPMFUT AS 'FUTURE DUE',
CURVCPMCUR AS 'CURRENT DUE',
CURVCPM30 AS 'PAST DUE 30',
CURVCPM60 AS 'PAST DUE 60',
CURVCPM90 AS 'PAST DUE 90', 
CURVCPM120 AS 'PAST DUE 120',
CURVCBLEOM AS ' TOTAL BALANCE DUE',
CULASPAYDT AS 'LAST PAY DATE',
CULASPAYAM AS 'LAST PAY AMOUNT'
FROM DTA273.TMCUST
WHERE CURVCBLEOM <>0;