SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT
    C.CUNUMBER AS "CUSTOMER #",
    C.CUNAME AS "CUSTOMER NAME",
    CASE
        WHEN TRIM(COALESCE(C.CUUSFLAG3, '')) <> '' THEN C.CUUSFLAG3
        WHEN TRIM(COALESCE(C.CUEXFLAG3, '')) = 'CC' THEN 'CC'
    END AS "CREDIT CARD CUSTOMER TYPE",
    COUNT(DISTINCT A.TARONUMINV) AS "UNPAID INVOICE COUNT",
    SUM(A.TAROAMTORG) AS "TOTAL UNPAID INVOICE AMOUNT",
    GROUP_CONCAT(
        DISTINCT A.TARONUMINV
        ORDER BY A.TARONUMINV
        SEPARATOR ', '
    ) AS "MISSING PAYMENT INVOICES"
FROM DTA273.TMCUST C
INNER JOIN DTA273.TMAROP A
    ON C.CUNUMBER = A.TARONUMCST
LEFT JOIN WEBLINK2.WEBPAYMENT W
    ON A.TARONUMINV = W.INVOICE
WHERE A.TARODTE = DATE_FORMAT(CURDATE() - INTERVAL 1 DAY, '%Y%m%d')
  AND (
        TRIM(COALESCE(C.CUUSFLAG3, '')) <> ''
        OR (
            TRIM(COALESCE(C.CUUSFLAG3, '')) = ''
            AND TRIM(COALESCE(C.CUEXFLAG3, '')) = 'CC'
        )
      )
  AND W.INVOICE IS NULL
GROUP BY
    C.CUNUMBER,
    C.CUNAME,
    CASE
        WHEN TRIM(COALESCE(C.CUUSFLAG3, '')) <> '' THEN C.CUUSFLAG3
        WHEN TRIM(COALESCE(C.CUEXFLAG3, '')) = 'CC' THEN 'CC'
    END
ORDER BY
    SUM(A.TAROAMTORG) DESC,
    C.CUNUMBER;