SELECT

    l.TIHLNUMCST AS "CUSTOMER #",
    l.TIHLNUMSTR AS "STORE #",
    l.TIHLNUMINV AS "INVOICE #",
    h.TIHHDTEINV AS "INVOICE DATE",
    h.TIHHTOTINV AS "INVOICE TOTAL",
    l.TIHLPRD AS "PRODUCT",
    CASE
        WHEN l.TIHLPRD = '99SLTAX' THEN -l.TIHLPRC
        ELSE l.TIHLPRC
    END AS "SALES TAX PRICE",
    h.TIHHSTECST AS "STATE",
    h.TIHHTAXAUT AS "TAX AUTHORITY",
    h.TIHHYRPRIN AS "PERIOD",
    h.TIHHVOIDYN AS "VOID Y/N"
FROM DTA273.TMIHSL l
JOIN DTA273.TMIHSH h
    ON h.TIHHNUMCST = l.TIHLNUMCST
   AND h.TIHHNUMINV = l.TIHLNUMINV
WHERE l.TIHLPRD IN ('SLTAX', '99SLTAX')
  AND l.TIHLPRC <> 0
  AND h.TIHHYRPRIN = 202605
  AND h.TIHHVOIDYN = 'N';