MODULES = [
    {
        "id": "dashboard",
        "title": "Dashboard",
        "version": "2.0.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "health", "recommendations", "ai"],
        "description": "Enterprise command center and system overview.",
        "keywords": ["home", "command center", "overview", "health"],
        "action": "Dashboard",
    },
    {
        "id": "assistant",
        "title": "AI Assistant",
        "version": "1.1.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "ai"],
        "description": "Local AI and indexed enterprise knowledge.",
        "keywords": ["ai", "knowledge", "chat", "ollama", "gemma"],
        "action": "AI Assistant",
    },
    {
        "id": "sql",
        "title": "SQL Studio",
        "version": "1.2.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "ai"],
        "description": "Read-only enterprise SQL workspace.",
        "keywords": [
            "query",
            "database",
            "mysql",
            "table",
            "product",
            "inventory",
        ],
        "action": "SQL Workspace",
    },
    {
        "id": "knowledge",
        "title": "SOP Search",
        "version": "1.1.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "ai"],
        "description": (
            "Search indexed company procedures and supporting documents."
        ),
        "keywords": [
            "sop",
            "procedure",
            "policy",
            "knowledge",
            "document",
        ],
        "action": "SOP Search",
    },
    {
        "id": "customer",
        "title": "Customer 360",
        "version": "1.1.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "health", "recommendations", "ai"],
        "description": "Customer, credit, aging, sales, and relationship intelligence.",
        "keywords": [
            "customer",
            "account",
            "credit",
            "aging",
            "sales",
            "route",
            "store",
            "risk",
            "high risk",
            "past due",
        ],
        "action": "Customer 360",
    },
    {
        "id": "cash-application",
        "title": "Cash Application",
        "version": "1.0.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "recommendations"],
        "description": "Payment matching and invoice allocation review.",
        "keywords": ["cash", "payment", "invoice", "remittance"],
        "action": "Cash Application",
    },
    {
        "id": "payment-notes",
        "title": "Payment Notes",
        "version": "0.1.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "recommendations"],
        "description": (
            "Reconcile PNC remote-capture checks to expected Payment Notes "
            "with explainable matching and durable review."
        ),
        "keywords": [
            "payment notes",
            "warehouse deposit",
            "remote capture",
            "virtual credit",
            "check reconciliation",
            "signature evidence",
        ],
        "action": "Payment Notes",
    },
    {
        "id": "credit-risk",
        "title": "Credit Risk",
        "version": "0.2.0",
        "status": "Ready",
        "capabilities": ["search", "timeline"],
        "description": (
            "Assessed-customer priority, alerts, source-grounded evidence, "
            "and append-only manual assessments."
        ),
        "keywords": [
            "credit risk",
            "manual rating",
            "assessment",
            "exposure",
            "review date",
            "priority alerts",
            "deterioration",
        ],
        "action": "Credit Risk",
    },
    {
        "id": "accounts-payable",
        "title": "Accounts Payable",
        "version": "0.1.0",
        "status": "Ready",
        "capabilities": ["search", "timeline"],
        "description": (
            "Imported vendor-invoice evidence, OCR review, exceptions, and "
            "duplicate candidates."
        ),
        "keywords": [
            "accounts payable",
            "ap invoice",
            "vendor invoice",
            "ocr review",
            "duplicate invoice",
            "exception review",
        ],
        "action": "Accounts Payable",
    },
    {
        "id": "financial-close",
        "title": "Financial Close",
        "version": "0.1.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "health"],
        "description": (
            "Local close-cycle controls, verified preparation ownership, "
            "and evidence-readiness review."
        ),
        "keywords": [
            "financial close",
            "close calendar",
            "close cycle",
            "control item",
            "preparer",
            "reviewer",
            "evidence readiness",
            "controller",
        ],
        "action": "Financial Close",
    },
    {
        "id": "reports",
        "title": "Report Builder",
        "version": "1.0.0",
        "status": "Ready",
        "capabilities": ["search", "timeline"],
        "description": "Reusable reports, parameters, exports, and previews.",
        "keywords": ["report", "export", "csv", "excel"],
        "action": "Report Builder",
    },
    {
        "id": "automation",
        "title": "Automation Center",
        "version": "1.0.0",
        "status": "Ready",
        "capabilities": ["search", "timeline", "recommendations"],
        "description": "Scheduled reports, scripts, run history, and delivery.",
        "keywords": ["schedule", "job", "script", "email"],
        "action": "Automation Center",
    },
    {
        "id": "documents",
        "title": "Document Intelligence",
        "version": "1.0.0",
        "status": "Ready",
        "capabilities": [
            "search",
            "timeline",
            "recommendations",
            "ai",
        ],
        "description": (
            "Classify, extract, review, train, and route enterprise documents."
        ),
        "keywords": [
            "document",
            "pdf",
            "ocr",
            "invoice",
            "lockbox",
            "pnc",
            "accounts payable",
            "training",
        ],
        "action": "Document Intelligence",
    },
    {
        "id": "projects",
        "title": "Project Tracker",
        "version": "0.1.0",
        "status": "Coming Soon",
        "capabilities": ["search", "timeline"],
        "description": (
            "Track transformation and technology projects."
        ),
        "keywords": [
            "project",
            "initiative",
            "transformation",
            "roadmap",
        ],
        "action": "Project Tracker",
    },
]
