import { FormEvent, useState } from 'react'
import './App.css'

type ModuleStatus = 'Ready' | 'Coming Soon'

type WorkbenchModule = {
  title: string
  description: string
  icon: string
  status: ModuleStatus
}

type ChatMessage = {
  role: 'user' | 'assistant'
  content: string
}

const modules: WorkbenchModule[] = [
  {
    title: 'AI Assistant',
    description: 'Chat with your local Ollama models.',
    icon: '🤖',
    status: 'Ready',
  },
  {
    title: 'SQL Workspace',
    description: 'Create, save, and organize SQL queries.',
    icon: '🗄️',
    status: 'Coming Soon',
  },
  {
    title: 'Report Builder',
    description: 'Build accounting and operational reports.',
    icon: '📊',
    status: 'Coming Soon',
  },
  {
    title: 'SOP Search',
    description: 'Search company procedures and documentation.',
    icon: '📄',
    status: 'Coming Soon',
  },
  {
    title: 'Automation Center',
    description: 'Manage PowerShell and Python automations.',
    icon: '⚙️',
    status: 'Coming Soon',
  },
  {
    title: 'Project Tracker',
    description: 'Track ERP modernization and improvement projects.',
    icon: '📁',
    status: 'Coming Soon',
  },
]

function App() {
  const [selectedModule, setSelectedModule] = useState('Dashboard')
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      role: 'assistant',
      content:
        'I am your local Enterprise AI Assistant. My responses are generated by Ollama on this computer.',
    },
  ])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')

  async function sendMessage(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()

    const trimmedInput = input.trim()

    if (!trimmedInput || isLoading) {
      return
    }

    const userMessage: ChatMessage = {
      role: 'user',
      content: trimmedInput,
    }

    const updatedMessages = [...messages, userMessage]

    setMessages(updatedMessages)
    setInput('')
    setError('')
    setIsLoading(true)

    try {
      const response = await fetch('http://127.0.0.1:8000/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: updatedMessages.map((message) => ({
            role: message.role,
            content: message.content,
          })),
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => null)

        throw new Error(
          errorData?.detail ?? `Backend request failed: ${response.status}`,
        )
      }

      const data: { response: string; model: string } = await response.json()

      setMessages((currentMessages) => [
        ...currentMessages,
        {
          role: 'assistant',
          content: data.response,
        },
      ])
    } catch (requestError) {
      const message =
        requestError instanceof Error
          ? requestError.message
          : 'Unable to reach the local AI backend.'

      setError(message)
    } finally {
      setIsLoading(false)
    }
  }

  function clearChat() {
    setMessages([
      {
        role: 'assistant',
        content:
          'Chat cleared. I am ready to help using the local Gemma model.',
      },
    ])
    setError('')
  }

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-icon">AI</div>

          <div>
            <h1>Enterprise AI</h1>
            <p>Workbench</p>
          </div>
        </div>

        <nav className="navigation">
          <button
            className={
              selectedModule === 'Dashboard' ? 'nav-item active' : 'nav-item'
            }
            onClick={() => setSelectedModule('Dashboard')}
          >
            <span>🏠</span>
            Dashboard
          </button>

          {modules.map((module) => (
            <button
              key={module.title}
              className={
                selectedModule === module.title
                  ? 'nav-item active'
                  : 'nav-item'
              }
              onClick={() => setSelectedModule(module.title)}
            >
              <span>{module.icon}</span>
              {module.title}
            </button>
          ))}
        </nav>

        <div className="sidebar-footer">
          <div className="system-status">
            <span className="status-dot" />

            <div>
              <strong>Local System</strong>
              <p>127.0.0.1 only</p>
            </div>
          </div>
        </div>
      </aside>

      <main className="main-content">
        <header className="top-bar">
          <div>
            <p className="eyebrow">LOCAL ENTERPRISE PLATFORM</p>
            <h2>{selectedModule}</h2>
          </div>

          <div className="user-card">
            <div className="user-avatar">JC</div>

            <div>
              <strong>Josh Corbit</strong>
              <p>Administrator</p>
            </div>
          </div>
        </header>

        {selectedModule === 'Dashboard' && (
          <>
            <section className="hero">
              <div>
                <span className="hero-label">Enterprise AI Workbench</span>

                <h3>
                  Your local command center for AI, reporting, and automation.
                </h3>

                <p>
                  Build internal tools, search company knowledge, generate SQL,
                  manage reports, and automate repetitive work from one secure
                  local platform.
                </p>

                <button
                  className="primary-button"
                  onClick={() => setSelectedModule('AI Assistant')}
                >
                  Open AI Assistant
                </button>
              </div>

              <div className="hero-stat">
                <span>Privacy status</span>
                <strong>Local Only</strong>
                <p>
                  React, FastAPI, and Ollama are configured for loopback access.
                </p>
              </div>
            </section>

            <section className="section-heading">
              <div>
                <p className="eyebrow">WORKSPACE</p>
                <h3>Applications</h3>
              </div>

              <span>{modules.length} modules</span>
            </section>

            <section className="module-grid">
              {modules.map((module) => (
                <button
                  className="module-card"
                  key={module.title}
                  onClick={() => setSelectedModule(module.title)}
                >
                  <div className="module-card-header">
                    <div className="module-icon">{module.icon}</div>

                    <span
                      className={
                        module.status === 'Ready'
                          ? 'module-status ready'
                          : 'module-status'
                      }
                    >
                      {module.status}
                    </span>
                  </div>

                  <h4>{module.title}</h4>
                  <p>{module.description}</p>

                  <div className="module-link">
                    Open module <span>→</span>
                  </div>
                </button>
              ))}
            </section>
          </>
        )}

        {selectedModule === 'AI Assistant' && (
          <section className="chat-page">
            <div className="chat-header">
              <div>
                <p className="eyebrow">OLLAMA LOCAL AI</p>
                <h3>Enterprise AI Assistant</h3>
                <p>Model: gemma3:12b · Connection: 127.0.0.1</p>
              </div>

              <button className="secondary-button" onClick={clearChat}>
                Clear chat
              </button>
            </div>

            <div className="chat-messages">
              {messages.map((message, index) => (
                <div
                  className={`chat-row ${message.role}`}
                  key={`${message.role}-${index}`}
                >
                  <div className="chat-avatar">
                    {message.role === 'user' ? 'JC' : 'AI'}
                  </div>

                  <div className="chat-bubble">
                    <strong>
                      {message.role === 'user' ? 'You' : 'Local Assistant'}
                    </strong>
                    <p>{message.content}</p>
                  </div>
                </div>
              ))}

              {isLoading && (
                <div className="chat-row assistant">
                  <div className="chat-avatar">AI</div>
                  <div className="chat-bubble">
                    <strong>Local Assistant</strong>
                    <p>Thinking locally…</p>
                  </div>
                </div>
              )}
            </div>

            {error && <div className="chat-error">{error}</div>}

            <form className="chat-form" onSubmit={sendMessage}>
              <textarea
                value={input}
                onChange={(event) => setInput(event.target.value)}
                placeholder="Ask your local AI assistant..."
                rows={3}
                disabled={isLoading}
              />

              <button
                className="send-button"
                type="submit"
                disabled={isLoading || !input.trim()}
              >
                {isLoading ? 'Generating…' : 'Send'}
              </button>
            </form>

            <p className="privacy-note">
              Local path: Browser → FastAPI → Ollama. No cloud AI API is
              configured.
            </p>
          </section>
        )}

        {selectedModule !== 'Dashboard' &&
          selectedModule !== 'AI Assistant' && (
            <section className="module-page">
              <div className="large-icon">
                {
                  modules.find(
                    (module) => module.title === selectedModule,
                  )?.icon
                }
              </div>

              <p className="eyebrow">MODULE</p>
              <h3>{selectedModule}</h3>

              <p>
                This module has been added to the application shell. Its working
                functionality will be built in a later phase.
              </p>

              <button
                className="secondary-button"
                onClick={() => setSelectedModule('Dashboard')}
              >
                Return to dashboard
              </button>
            </section>
          )}
      </main>
    </div>
  )
}

export default App